#!/usr/bin/env python3
"""
Enhanced Cache Miss Records Analysis Script
Modified by wei wu on 250816

This script analyzes cache miss records generated by the extended ZSim with 
hierarchical PC->MissType->Records structure. Supports batch processing of 
multiple subdirectories and cache hierarchy analysis.
"""

import h5py
import numpy as np
import argparse
import os
import sys
import glob
from collections import defaultdict, Counter
import re

class CacheMissAnalyzer:
    def __init__(self):
        self.cache_hierarchy = {
            'l1i': 'l1i',  # L1 instruction cache
            'l1d': 'l1d',  # L1 data cache  
            'l2': 'l2',    # L2 cache
            'l3': 'l3'     # L3 cache (shared)
        }
        
    def parse_cache_info(self, filename):
        """Parse cache type and instance number from filename."""
        # Extract cache type and instance from filename like cache_miss_records_l1i-0.h5
        match = re.search(r'cache_miss_records_([a-z0-9]+)-(\d+)\.h5', filename)
        if match:
            cache_type = match.group(1)
            instance = int(match.group(2))
            return cache_type, instance
        return None, None
    
    def analyze_cache_file(self, filepath):
        """Analyze a single cache miss records file."""
        filename = os.path.basename(filepath)
        cache_type, instance = self.parse_cache_info(filename)
        
        if cache_type is None:
            print(f"Warning: Could not parse cache info from {filename}")
            return None
            
        print(f"Analyzing {filename} ({cache_type}-{instance})...")
        
        try:
            with h5py.File(filepath, 'r') as f:
                # Get cache group (should be the first and only group)
                cache_groups = list(f.keys())
                if not cache_groups:
                    print(f"No cache groups found in {filename}")
                    return None
                
                cache_name = cache_groups[0]
                cache_group = f[cache_name]
                
                # Get metadata
                total_records = cache_group['total_records'][0]
                unique_pcs = cache_group['unique_pcs'][0]
                
                # Collect PC miss statistics with detailed information
                pc_miss_stats = {}
                
                # Iterate through all PCs
                for pc_group_name in cache_group.keys():
                    if pc_group_name.startswith('PC_0x'):
                        pc_group = cache_group[pc_group_name]
                        pc_value = int(pc_group_name[5:], 16)
                        
                        pc_total_misses = 0
                        miss_type_counts = {'mGETS': 0, 'mGETXIM': 0, 'mGETXSM': 0}
                        all_cycles = []
                        all_addresses = []
                        
                        # Check each miss type
                        for miss_type in ['mGETS', 'mGETXIM', 'mGETXSM']:
                            if miss_type in pc_group:
                                type_group = pc_group[miss_type]
                                cycles = type_group['cycle'][:]
                                addresses = type_group['address'][:]
                                count = len(cycles)
                                
                                miss_type_counts[miss_type] = count
                                pc_total_misses += count
                                all_cycles.extend(cycles)
                                all_addresses.extend(addresses)
                        
                        if pc_total_misses > 0:
                            pc_miss_stats[pc_value] = {
                                'total_misses': pc_total_misses,
                                'miss_types': miss_type_counts,
                                'cache_type': cache_type,
                                'instance': instance,
                                'cycles': all_cycles,
                                'addresses': all_addresses,
                                'cycle_range': (min(all_cycles), max(all_cycles)) if all_cycles else (0, 0),
                                'address_range': (min(all_addresses), max(all_addresses)) if all_addresses else (0, 0)
                            }
                
                return {
                    'filename': filename,
                    'cache_type': cache_type,
                    'instance': instance,
                    'total_records': total_records,
                    'unique_pcs': unique_pcs,
                    'pc_miss_stats': pc_miss_stats
                }
                
        except Exception as e:
            print(f"Error analyzing {filename}: {e}")
            return None
    
    def calculate_cache_hierarchy_access(self, all_cache_data):
        """Calculate access counts based on cache hierarchy."""
        # Group by cache type and instance
        cache_data_by_type = defaultdict(dict)
        for data in all_cache_data:
            if data:
                cache_type = data['cache_type']
                instance = data['instance']
                cache_data_by_type[cache_type][instance] = data
        
        # Calculate L2 access counts (L1i + L1d misses)
        l2_access_counts = defaultdict(int)
        for l2_instance in cache_data_by_type.get('l2', {}):
            l2_data = cache_data_by_type['l2'][l2_instance]
            l1i_data = cache_data_by_type.get('l1i', {}).get(l2_instance)
            l1d_data = cache_data_by_type.get('l1d', {}).get(l2_instance)
            
            # L2 access count = L1i misses + L1d misses for this core
            l1i_misses = sum(pc['total_misses'] for pc in l1i_data['pc_miss_stats'].values()) if l1i_data else 0
            l1d_misses = sum(pc['total_misses'] for pc in l1d_data['pc_miss_stats'].values()) if l1d_data else 0
            l2_access_counts[l2_instance] = l1i_misses + l1d_misses
        
        # Calculate L3 access counts (sum of all L2 misses)
        l3_access_counts = defaultdict(int)
        for l3_instance in cache_data_by_type.get('l3', {}):
            l3_data = cache_data_by_type['l3'][l3_instance]
            # L3 access count = sum of all L2 misses
            total_l2_misses = sum(pc['total_misses'] for l2_data in cache_data_by_type.get('l2', {}).values() 
                                for pc in l2_data['pc_miss_stats'].values())
            l3_access_counts[l3_instance] = total_l2_misses
        
        return l2_access_counts, l3_access_counts
    
    def aggregate_pc_stats(self, all_cache_data, l2_access_counts, l3_access_counts):
        """Aggregate PC statistics across all caches with hierarchy access counts."""
        pc_aggregate_stats = defaultdict(lambda: {
            'total_misses': 0,
            'cache_breakdown': defaultdict(int),
            'access_counts': defaultdict(int),
            'detailed_stats': defaultdict(dict)
        })
        
        for data in all_cache_data:
            if not data:
                continue
                
            cache_type = data['cache_type']
            instance = data['instance']
            cache_key = f"{cache_type}-{instance}"
            
            for pc_value, pc_stats in data['pc_miss_stats'].items():
                pc_aggregate_stats[pc_value]['total_misses'] += pc_stats['total_misses']
                pc_aggregate_stats[pc_value]['cache_breakdown'][cache_key] += pc_stats['total_misses']
                
                # Store detailed stats for each cache instance
                pc_aggregate_stats[pc_value]['detailed_stats'][cache_key] = {
                    'misses': pc_stats['total_misses'],
                    'miss_types': pc_stats['miss_types'],
                    'cycle_range': pc_stats['cycle_range'],
                    'address_range': pc_stats['address_range'],
                    'cache_type': cache_type,
                    'instance': instance
                }
                
                # Set access counts based on cache hierarchy
                if cache_type == 'l1i' or cache_type == 'l1d':
                    # L1 caches: access count = miss count (no hierarchy consideration)
                    pc_aggregate_stats[pc_value]['access_counts'][cache_key] = pc_stats['total_misses']
                elif cache_type == 'l2':
                    # L2 cache: access count from hierarchy calculation
                    pc_aggregate_stats[pc_value]['access_counts'][cache_key] = l2_access_counts.get(instance, 0)
                elif cache_type == 'l3':
                    # L3 cache: access count from hierarchy calculation
                    pc_aggregate_stats[pc_value]['access_counts'][cache_key] = l3_access_counts.get(instance, 0)
        
        return pc_aggregate_stats
    
    def analyze_directory(self, directory_path):
        """Analyze all cache miss files in a directory."""
        print(f"\n=== Analyzing directory: {directory_path} ===")
        
        # Find all cache miss record files
        pattern = os.path.join(directory_path, "cache_miss_records_*.h5")
        cache_files = glob.glob(pattern)
        
        if not cache_files:
            print(f"No cache miss record files found in {directory_path}")
            return None
        
        print(f"Found {len(cache_files)} cache miss record files")
        
        # Analyze each cache file
        all_cache_data = []
        for filepath in sorted(cache_files):
            cache_data = self.analyze_cache_file(filepath)
            all_cache_data.append(cache_data)
        
        # Calculate cache hierarchy access counts
        l2_access_counts, l3_access_counts = self.calculate_cache_hierarchy_access(all_cache_data)
        
        # Aggregate PC statistics
        pc_aggregate_stats = self.aggregate_pc_stats(all_cache_data, l2_access_counts, l3_access_counts)
        
        return {
            'directory': directory_path,
            'cache_data': all_cache_data,
            'pc_stats': pc_aggregate_stats,
            'l2_access_counts': l2_access_counts,
            'l3_access_counts': l3_access_counts
        }
    
    def print_top_pcs_by_cache_instance(self, analysis_results, top_n=10):
        """Print top N PCs for each cache instance with detailed information."""
        print(f"\n=== Top {top_n} PCs by Cache Instance ===")
        
        # Group by cache instance
        cache_instance_stats = defaultdict(list)
        
        for result in analysis_results:
            if result:
                for pc_value, stats in result['pc_stats'].items():
                    for cache_key, detailed_stats in stats['detailed_stats'].items():
                        cache_instance_stats[cache_key].append({
                            'pc_value': pc_value,
                            'misses': detailed_stats['misses'],
                            'miss_types': detailed_stats['miss_types'],
                            'cycle_range': detailed_stats['cycle_range'],
                            'address_range': detailed_stats['address_range'],
                            'cache_type': detailed_stats['cache_type'],
                            'instance': detailed_stats['instance'],
                            'access_count': stats['access_counts'].get(cache_key, 0),
                            'directory': result['directory']
                        })
        
        # Print top N for each cache instance
        for cache_key in sorted(cache_instance_stats.keys()):
            cache_stats = cache_instance_stats[cache_key]
            
            # Sort by misses (descending)
            sorted_pcs = sorted(cache_stats, key=lambda x: x['misses'], reverse=True)
            
            print(f"\n--- {cache_key.upper()} Cache ---")
            print(f"Total PCs with misses: {len(sorted_pcs)}")
            
            # Print top N
            for i, pc_stats in enumerate(sorted_pcs[:top_n], 1):
                pc_value = pc_stats['pc_value']
                misses = pc_stats['misses']
                access_count = pc_stats['access_count']
                cache_type = pc_stats['cache_type']
                
                # Calculate miss rate (except for L1 caches)
                miss_rate = 0.0
                if cache_type not in ['l1i', 'l1d'] and access_count > 0:
                    miss_rate = (misses / access_count) * 100
                
                print(f"\n{i:2d}. PC 0x{pc_value:x}")
                print(f"    Misses: {misses:,}")
                if cache_type not in ['l1i', 'l1d']:
                    print(f"    Access Count: {access_count:,}")
                    print(f"    Miss Rate: {miss_rate:.2f}%")
                
                # Print miss type breakdown
                miss_types = pc_stats['miss_types']
                print(f"    Miss Types: GETS={miss_types['mGETS']}, GETXIM={miss_types['mGETXIM']}, GETXSM={miss_types['mGETXSM']}")
                
                # Print ranges
                cycle_range = pc_stats['cycle_range']
                address_range = pc_stats['address_range']
                print(f"    Cycle Range: {cycle_range[0]:,} - {cycle_range[1]:,}")
                print(f"    Address Range: 0x{address_range[0]:x} - 0x{address_range[1]:x}")
                
                # Print directory
                print(f"    Directory: {os.path.basename(pc_stats['directory'])}")
    
    def print_top_pcs(self, analysis_results, top_n=10):
        """Print top N PCs by total miss count across all caches."""
        print(f"\n=== Top {top_n} PCs by Total Miss Count (All Caches) ===")
        
        # Collect all PC stats from all directories
        all_pc_stats = {}
        for result in analysis_results:
            if result:
                for pc_value, stats in result['pc_stats'].items():
                    if pc_value not in all_pc_stats:
                        all_pc_stats[pc_value] = {
                            'total_misses': 0,
                            'cache_breakdown': defaultdict(int),
                            'access_counts': defaultdict(int),
                            'directories': []
                        }
                    
                    all_pc_stats[pc_value]['total_misses'] += stats['total_misses']
                    for cache_key, count in stats['cache_breakdown'].items():
                        all_pc_stats[pc_value]['cache_breakdown'][cache_key] += count
                    for cache_key, count in stats['access_counts'].items():
                        all_pc_stats[pc_value]['access_counts'][cache_key] += count
                    all_pc_stats[pc_value]['directories'].append(result['directory'])
        
        # Sort by total misses (descending)
        sorted_pcs = sorted(all_pc_stats.items(), key=lambda x: x[1]['total_misses'], reverse=True)
        
        # Print top N
        for i, (pc_value, stats) in enumerate(sorted_pcs[:top_n], 1):
            print(f"\n{i:2d}. PC 0x{pc_value:x}: {stats['total_misses']:,} total misses")
            print(f"    Directories: {', '.join(os.path.basename(d) for d in stats['directories'])}")
            
            # Print cache breakdown
            if stats['cache_breakdown']:
                print("    Cache breakdown:")
                for cache_key, count in sorted(stats['cache_breakdown'].items()):
                    access_count = stats['access_counts'].get(cache_key, 0)
                    print(f"      {cache_key}: {count:,} misses (access: {access_count:,})")
    
    def print_cache_summary(self, analysis_results):
        """Print summary statistics for each cache type."""
        print(f"\n=== Cache Summary Statistics ===")
        
        cache_totals = defaultdict(lambda: {'misses': 0, 'accesses': 0, 'instances': 0})
        
        for result in analysis_results:
            if result:
                for data in result['cache_data']:
                    if data:
                        cache_type = data['cache_type']
                        cache_totals[cache_type]['misses'] += data['total_records']
                        cache_totals[cache_type]['instances'] += 1
                        
                        # Add access counts from hierarchy
                        if cache_type == 'l2':
                            for instance, access_count in result['l2_access_counts'].items():
                                cache_totals[cache_type]['accesses'] += access_count
                        elif cache_type == 'l3':
                            for instance, access_count in result['l3_access_counts'].items():
                                cache_totals[cache_type]['accesses'] += access_count
                        else:  # L1 caches
                            cache_totals[cache_type]['accesses'] += data['total_records']
        
        for cache_type in sorted(cache_totals.keys()):
            stats = cache_totals[cache_type]
            print(f"{cache_type.upper()}: {stats['misses']:,} misses, {stats['accesses']:,} accesses, {stats['instances']} instances")

def main():
    parser = argparse.ArgumentParser(description='Enhanced cache miss records analysis from ZSim')
    parser.add_argument('paths', nargs='*', help='Directories to analyze (default: current directory)')
    parser.add_argument('--top', type=int, default=10, help='Number of top PCs to show (default: 10)')
    parser.add_argument('--recursive', action='store_true', help='Recursively search subdirectories for cache files')
    parser.add_argument('--by-cache', action='store_true', help='Show top PCs by cache instance (default: True)')
    parser.add_argument('--by-total', action='store_true', help='Show top PCs by total miss count across all caches')
    
    args = parser.parse_args()
    
    analyzer = CacheMissAnalyzer()
    
    # Determine paths to analyze
    if args.paths:
        paths = args.paths
    else:
        paths = ['.']
    
    # Find all directories to analyze
    all_directories = []
    for path in paths:
        if os.path.isdir(path):
            if args.recursive:
                # Recursively find all subdirectories
                for root, dirs, files in os.walk(path):
                    # Check if this directory contains cache miss files
                    cache_files = glob.glob(os.path.join(root, "cache_miss_records_*.h5"))
                    if cache_files:
                        all_directories.append(root)
            else:
                all_directories.append(path)
        else:
            print(f"Warning: {path} is not a directory, skipping")
    
    if not all_directories:
        print("No valid directories found to analyze")
        sys.exit(1)
    
    print(f"Found {len(all_directories)} directory(ies) to analyze")
    
    # Analyze each directory
    analysis_results = []
    for directory in sorted(all_directories):
        result = analyzer.analyze_directory(directory)
        analysis_results.append(result)
    
    # Print results
    if args.by_cache or (not args.by_total and not args.by_cache):  # Default to by-cache if no specific option
        analyzer.print_top_pcs_by_cache_instance(analysis_results, args.top)
    
    if args.by_total:
        analyzer.print_top_pcs(analysis_results, args.top)
    
    analyzer.print_cache_summary(analysis_results)

if __name__ == '__main__':
    main() 